[default_config]
assembler = "nasm"
instruction_set = "x86/x86-64"

[default_config.opts]
compiler = "nasm"
diagnostics = true
default_diagnostics = true
compile_flags_txt = ["-f", "elf64"]

[[project]]
path = "src/arm/gba"
assembler = "gas"
instruction_set = "arm"

[project.opts]
compiler = "arm-none-eabi-gcc"
diagnostics = true
default_diagnostics = true
compile_flags_txt = [
    "-mcpu=arm7tdmi",
    "-mthumb-interwork",
    "-c"
]
